# Generated by Django 2.1.7 on 2019-05-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_hidepostfrom_postcomments_postimage_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='post_images'),
        ),
    ]
