# Generated by Django 2.1.7 on 2019-05-15 01:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20190514_2335'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostComments',
            new_name='PostComment',
        ),
    ]
