# Generated by Django 2.1.7 on 2019-05-16 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_auto_20190515_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='HidePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='hidepostfrom',
            name='author',
        ),
        migrations.RemoveField(
            model_name='hidepostfrom',
            name='post',
        ),
        migrations.DeleteModel(
            name='HidePostFrom',
        ),
    ]
