# Generated by Django 2.1.7 on 2019-05-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofil',
            old_name='ano',
            new_name='matriculas',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='facebook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='instagram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='profil_image',
            field=models.ImageField(default='default_profile_pic.png', upload_to='profile_pic'),
        ),
        migrations.AddField(
            model_name='userprofil',
            name='twitter',
            field=models.CharField(default='', max_length=50),
        ),
    ]
