# Generated by Django 2.1.7 on 2019-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190511_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofil',
            name='matriculas',
        ),
        migrations.AddField(
            model_name='userprofil',
            name='n_matriculas',
            field=models.IntegerField(default=0),
        ),
    ]
