# Generated by Django 2.1.7 on 2019-05-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190512_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='profil_image',
            field=models.ImageField(default='default_user_profile_pic.png', upload_to='profile_pic'),
        ),
    ]
