# Generated by Django 2.1.7 on 2019-05-16 06:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190516_0637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersbloqueados',
            name='ocultados',
            field=models.ManyToManyField(default='', related_name='bloqueado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersbloqueados',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_bloqueados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersocultados',
            name='ocultados',
            field=models.ManyToManyField(default='', related_name='ocultado_por', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usersocultados',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_ocultados', to=settings.AUTH_USER_MODEL),
        ),
    ]
