# Generated by Django 2.1.7 on 2019-05-16 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190516_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersbloqueados',
            old_name='ocultados',
            new_name='bloqueados',
        ),
    ]
